AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template for deploying knowledge bot RAG resources: Amazon Kendra Index, S3 bucket and corresponding IAM roles"
Parameters:
  InstanceType:
    Type: String
    Description: SageMaker Endpoint Instance Type
    Default: ml.g5.12xlarge
Mappings:
  ModelPackageMap:
    us-east-1: 
      ModelPackage: "arn:aws:sagemaker:us-east-1:865070037744:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    us-east-2: 
      ModelPackage: "arn:aws:sagemaker:us-east-2:057799348421:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    us-west-1: 
      ModelPackage: "arn:aws:sagemaker:us-west-1:382657785993:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    us-west-2: 
      ModelPackage: "arn:aws:sagemaker:us-west-2:594846645681:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    ca-central-1: 
      ModelPackage: "arn:aws:sagemaker:ca-central-1:470592106596:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    eu-central-1: 
      ModelPackage: "arn:aws:sagemaker:eu-central-1:446921602837:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    eu-west-1: 
      ModelPackage: "arn:aws:sagemaker:eu-west-1:985815980388:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    eu-west-2: 
      ModelPackage: "arn:aws:sagemaker:eu-west-2:856760150666:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    eu-west-3: 
      ModelPackage: "arn:aws:sagemaker:eu-west-3:843114510376:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    eu-north-1: 
      ModelPackage: "arn:aws:sagemaker:eu-north-1:136758871317:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    ap-southeast-1: 
      ModelPackage: "arn:aws:sagemaker:ap-southeast-1:192199979996:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    ap-southeast-2: 
      ModelPackage: "arn:aws:sagemaker:ap-southeast-2:666831318237:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    ap-northeast-2: 
      ModelPackage: "arn:aws:sagemaker:ap-northeast-2:745090734665:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    ap-northeast-1: 
      ModelPackage: "arn:aws:sagemaker:ap-northeast-1:977537786026:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    ap-south-1: 
      ModelPackage: "arn:aws:sagemaker:ap-south-1:077584701553:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
    sa-east-1: 
      ModelPackage: "arn:aws:sagemaker:sa-east-1:270155090741:model-package/j2-grande-instruct-v1-1-43-b1704f916990312a8e21b249a0bd479c"
Resources:
  KendraRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "KendraRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "kendra.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonKendraFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess"
        - "arn:aws:iam::aws:policy/CloudWatchLogsFullAccess"
  SageMakerRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "SageMakerRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "sagemaker.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
  KendraIndex:
    Type: "AWS::Kendra::Index"
    Properties:
      Name: "MyKendraIndex"
      RoleArn: !GetAtt KendraRole.Arn
      Edition: "DEVELOPER_EDITION"
  WebDataS3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      AccessControl: "Private"
  Model:
    Type: AWS::SageMaker::Model
    Properties:
      EnableNetworkIsolation: true
      ExecutionRoleArn: !GetAtt SageMakerRole.Arn
      PrimaryContainer:
        ModelPackageName: !FindInMap
          - ModelPackageMap
          - !Ref 'AWS::Region'
          - ModelPackage
  EndpointConfig:
    Type: "AWS::SageMaker::EndpointConfig"
    Properties:
      ProductionVariants:
        - ModelName: !GetAtt Model.ModelName
          VariantName: llmscrape
          InitialInstanceCount: 1
          InitialVariantWeight: 1.0
          InstanceType: !Ref InstanceType
  SageMakerEndpoint:
    Type: "AWS::SageMaker::Endpoint"
    Properties:
      EndpointConfigName: !GetAtt EndpointConfig.EndpointConfigName
